services:
  code:
    image: lscr.io/linuxserver/code-server:4.101.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Toronto"
      PASSWORD: "${PASSWORD}"
      GH_USER: "${GH_USER}"          # optional for auto-run; required for manual run
      GH_PAT: "${GH_PAT}"            # optional for auto-run; required for manual run
      GIT_NAME: "${GIT_NAME}"
      GIT_EMAIL: "${GIT_EMAIL}"
      GIT_REPOS: "${GIT_REPOS}"
      GIT_BASE_DIR: "/config/workspace"
    volumes:
      - code-config:/config
      - projects:/config/workspace
      - ./bootstrap.sh:/config/bin/bootstrap.sh:ro
      - ./init/00-bootstrap-on-start.sh:/custom-cont-init.d/00-bootstrap-on-start.sh:ro
    ports:
      - ":8443"
    restart: always

volumes:
  code-config:
  projects:
