services:
  code:
    image: lscr.io/linuxserver/code-server:4.101.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Toronto"
      PASSWORD: "${PASSWORD}"
      GIT_NAME: "${GIT_NAME}"
      GIT_EMAIL: "${GIT_EMAIL}"
      GIT_REPOS: "${GIT_REPOS}"
      GIT_BASE_DIR: "/config/workspace"
    volumes:
      - code-config:/config
      - projects:/config/workspace
      - ./init/10-git.sh:/custom-cont-init.d/10-git.sh:ro
      - ./init/20-vscode-settings.sh:/custom-cont-init.d/20-vscode-settings.sh:ro
      - ssh-keys:/root/.ssh  # Make sure this is read-write
    ports:
      - ":8443"
    restart: unless-stopped

volumes:
  code-config: {}
  projects: {}
  ssh-keys: {}  # Make sure this volume is read-write
