services:
  code:
    image: lscr.io/linuxserver/code-server:4.101.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Toronto"
      PASSWORD: "${PASSWORD}"
      GH_USER: "${GH_USER}"        # optional for autorun; required for manual task
      GH_PAT: "${GH_PAT}"          # optional for autorun; required for manual task
      GIT_NAME: "${GIT_NAME}"
      GIT_EMAIL: "${GIT_EMAIL}"
      GIT_REPOS: "${GIT_REPOS}"
      GIT_BASE_DIR: "/config/workspace"
    volumes:
      - code-config:/config-1
      - code-config:/config
      - projects:/config/workspace
      - ./init/10-bootstrap.sh:/custom-cont-init.d/10-bootstrap.sh:ro
    ports:
      - ":8443"
    restart: always

volumes:
  code-config:
  projects:
