services:
  code:
    image: lscr.io/linuxserver/code-server:4.101.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Toronto"
      PASSWORD: "${PASSWORD}"
      GIT_NAME: "${GIT_NAME}"
      GIT_EMAIL: "${GIT_EMAIL}"
      GIT_REPOS: "${GIT_REPOS}"
      GIT_BASE_DIR: "/config/workspace"
      GH_PAT: "${GH_PAT}"
    volumes:
      - code-config:/config                 # abc's HOME
      - projects:/config/workspace
      - ./init/10-git.sh:/custom-cont-init.d/10-git.sh:ro
      - ./init/20-vscode-settings.sh:/custom-cont-init.d/20-vscode-settings.sh:ro
    ports:
      - ":8443"
    restart: always

volumes:
  code-config: {}
  projects: {}
