services:
  code:
    image: lscr.io/linuxserver/code-server:4.101.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Toronto"
      FILE__PASSWORD: "/config/.gitstrap/codepass.txt"
      GH_USER: "${GH_USER}"
      GH_PAT: "${GH_PAT}"
      GIT_NAME: "${GIT_NAME}"
      GIT_EMAIL: "${GIT_EMAIL}"
      GIT_REPOS: "${GIT_REPOS}"
      GIT_BASE_DIR: "/config/workspace"
    volumes:
      - code-config:/config
      - projects:/config/workspace
      - ./settings.json:/config/gitstrap/settings.json:ro
      - ./gitstrap.sh:/custom-cont-init.d/10-gitstrap.sh:ro
      - ./restartgate.sh:/custom-cont-init.d/01-restartgate.sh:ro   # <— add this
      - ./codepass.sh:/custom-cont-init.d/20-codepass.sh:ro
    ports:
      - ":8443"
    restart: always

volumes:
  code-config:
  projects:
