services:
  code:
    image: lscr.io/linuxserver/code-server:4.101.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Toronto"
      PASSWORD: "${PASSWORD}"
      # --- Git bootstrap (minimal) ---
      GH_USER: "${GH_USER}"        # required (username)
      GH_PAT: "${GH_PAT}"          # required (token; scopes: user:email, admin:public_key)
      GIT_NAME: "${GIT_NAME}"      # optional; defaults to GH_USER if empty
      GIT_REPOS: "${GIT_REPOS}"    # owner/repo[#branch] or https URLs, comma-separated
      GIT_BASE_DIR: "/config/workspace"
    volumes:
      - code-config:/config
      - projects:/config/workspace
      - ./init/10-git.sh:/custom-cont-init.d/10-git.sh:ro
    ports:
      - ":8443"
    restart: always

volumes:
  code-config:
  projects:
